name: CI
# This workflow represents a set of basic End-to-End tests
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  publish-on-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: 'main'
      - uses: actions/setup-node@master
        with:
          node-version: 18.10
      - name: Install dependencies
        run: npm ci
      - name: Build on MacOS && Publish
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        run: npm run publish
  publish-on-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: 'main'
      - uses: actions/setup-node@master
        with:
          node-version: 18.10
      - name: Install dependencies
        run: npm ci
      - name: Build on Windows && Publish
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        run: npm run publish

